import { mkdirSync, writeFileSync, readFileSync } from 'node:fs'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { resolve, join } from 'node:path'
import assert from 'node:assert/strict'
import { setupE2E, rpc as callRpc, modelSelector } from './support.mjs'

const { desktop, output, env, launch } = setupE2E('electron-e2e')
const errors = []
const checks = []
const record = (name, evidence) => { checks.push({ name, evidence }); console.log(name, JSON.stringify(evidence)) }
const app = await launch()
try {
  const page = await app.firstWindow()
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.waitForSelector('.app-shell', { timeout: 30_000 })
  const rpc = (method, params = {}) => callRpc(page, method, params)
  const baseline = await rpc('app.bootstrap')
  assert.equal(page.url(), 'singularity://app/')
  assert.equal(await page.evaluate(() => typeof window.require), 'undefined')
  record('desktop-start', { url: page.url(), generation: baseline.generation, workspaces: baseline.workspaces.length })
  await page.screenshot({ path: join(output, 'startup.png') })
  writeFileSync(join(output, 'ui.txt'), await page.locator('body').innerText())
  record('rendered-controls', await page.getByRole('button').allTextContents())
  const nativeDialog = async (cancel = false) => {
    const workspace = resolve(output, 'workspace')
    mkdirSync(workspace, { recursive: true })
    const action = promisify(execFile)('pwsh.exe', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', join(desktop, 'e2e/folder-dialog.ps1'), '-OwnerProcessId', String(await app.evaluate(() => process.pid)), ...(cancel ? ['-Cancel'] : ['-Folder', workspace])], { timeout: 25_000 })
    await page.getByRole('button', { name: '添加项目', exact: true }).click()
    try { record(cancel ? 'folder-cancel' : 'folder-select', (await action).stdout.trim()) } catch(error) { console.log(await page.locator('body').innerText()); throw error }
  }
  await nativeDialog(true)
  assert.equal((await rpc('app.bootstrap')).workspaces.length, baseline.workspaces.length)
  await nativeDialog()
  await page.waitForFunction(() => document.querySelector('.workspace-new'))
  const workspace = (await rpc('app.bootstrap')).workspaces.find(item => item.root.replaceAll('\\', '/').endsWith('/workspace'))
  assert.ok(workspace)
  await page.getByRole('button', { name: `在 ${workspace.name} 新建任务`, exact: true }).click()
  const textarea = page.getByRole('textbox', { name: '任务说明' })
  await textarea.fill('desktop draft persistence')
  await page.reload()
  await page.waitForFunction(() => document.querySelector('textarea[aria-label="任务说明"]')?.value === 'desktop draft persistence')
  assert.equal((await rpc('app.bootstrap')).generation, baseline.generation)
  record('reload-draft-and-backend', true)
  await page.getByRole('button', { name: '展开任务工具', exact: true }).click()
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByRole('spinbutton', { name: '消息字号' }).fill('18')
  await page.waitForTimeout(400)
  await page.screenshot({ path: join(output, 'settings.png') })
  await page.getByRole('button', { name: '关闭设置', exact: true }).click()
  const widths = page.evaluate(async () => { const samples = []; const start = performance.now(); while (performance.now() - start < 600) { samples.push(document.querySelector('.sidebar-shell').getBoundingClientRect().width); await new Promise(requestAnimationFrame) } return samples })
  await page.getByRole('button', { name: '关闭左侧栏', exact: true }).click()
  const samples = await widths
  assert.ok(new Set(samples.map(value => Math.round(value))).size > 3)
  record('sidebar-animation-widths', samples)
  await page.waitForTimeout(400)
  await page.screenshot({ path: join(output, 'sidebar-collapsed.png') })
  await page.getByRole('button', { name: '打开左侧栏', exact: true }).click()
  await page.getByRole('button', { name: '打开右侧栏', exact: true }).click()
  await page.getByRole('button', { name: '轨迹', exact: true }).click()
  await page.waitForTimeout(400)
  await page.screenshot({ path: join(output, 'trajectory.png') })
  await page.getByRole('button', { name: '关闭右侧栏', exact: true }).click()
  record('settings-and-panels', true)
  const window = await app.browserWindow(page)
  await window.evaluate(window => window.close())
  assert.equal(await window.evaluate(window => window.isVisible()), false)
  assert.equal((await rpc('app.bootstrap')).generation, baseline.generation)
  const launch = await app.evaluate(({ app }) => ({ exe: app.getPath('exe'), path: app.getAppPath(), packaged: app.isPackaged }))
  await promisify(execFile)(launch.exe, launch.packaged ? [] : [launch.path], { env, timeout: 20_000 })
  assert.equal(await window.evaluate(window => window.isVisible()), true)
  record('close-hides-second-launch-reopens', true)
  const canvases = page.locator('canvas')
  const firstImage = await canvases.first().evaluate(canvas => canvas.toDataURL())
  await page.waitForTimeout(250)
  assert.notEqual(await canvases.first().evaluate(canvas => canvas.toDataURL()), firstImage)
  record('canvas-animation', true)
  await page.getByRole('button', { name: '展开任务工具', exact: true }).click()
  await page.getByRole('button', { name: '切换深色模式', exact: true }).click()
  await page.waitForTimeout(600)
  await page.screenshot({ path: join(output, 'dark.png') })
  const darkImage = await canvases.first().evaluate(canvas => canvas.toDataURL())
  await page.waitForTimeout(250)
  assert.notEqual(await canvases.first().evaluate(canvas => canvas.toDataURL()), darkImage)
  await page.getByRole('button', { name: '切换浅色模式', exact: true }).click()
  await textarea.click()
  record('theme-and-dark-canvas', true)
  if (process.env.SINGULARITY_E2E_MODEL === '1') {
    const selection = await page.evaluate(() => JSON.parse(localStorage.getItem('singularity.app.view.v1')))
    const sessionId = selection.selectedSessionId
    const scope = { workspaceId: workspace.workspaceId, sessionId }
    await rpc('session.updateSettings', { ...scope, selector: modelSelector })
    writeFileSync(join(output, 'workspace/fixture.txt'), 'ELECTRON_PIPE_FIXTURE_20260925\n')
    await page.evaluate(() => { window.__frames = []; window.singularity.onFrame(frame => window.__frames.push(frame)) })
    const prompt = '这是桌面端端到端验证，仅在当前目录操作。先使用 bash 执行 sleep 20，然后读取 fixture.txt，把该文件内容原样写入 result.txt。最后用中文简短报告结果，并给出一个包含 ELECTRON_PIPE_OK 的代码块。请实际调用工具，不要只描述步骤。'
    await textarea.fill(prompt)
    await page.getByRole('button', { name: '发送消息', exact: true }).click()
    await page.waitForFunction(() => window.__frames.some(frame => frame.type === 'turn_event' && frame.payload.method === 'tool/execution/start'), undefined, { timeout: 180_000 })
    record('real-model-tool-start', sessionId)
    await textarea.fill('此排队输入将被撤回，不要执行。')
    await textarea.press('Enter')
    await page.getByRole('button', { name: '删除排队消息', exact: true }).click()
    record('queue-and-withdraw', true)
    await page.screenshot({ path: join(output, 'streaming.png') })
    const beforeReload = await page.evaluate(() => window.__frames)
    await window.evaluate(window => window.close())
    await page.waitForTimeout(1500)
    assert.notEqual((await rpc('session.read', { ...scope, limit: 40, beforeTurn: null })).runtime.phase, 'idle')
    await window.evaluate(window => window.show())
    await page.reload()
    await page.waitForSelector('.app-shell')
    await page.evaluate(() => { window.__frames = []; window.singularity.onFrame(frame => window.__frames.push(frame)) })
    assert.equal((await rpc('app.bootstrap')).generation, baseline.generation)
    record('running-hide-and-reload', true)
    const deadline = Date.now() + 180_000
    let result
    do {
      result = await rpc('session.read', { ...scope, limit: 40, beforeTurn: null })
      if (result.runtime.phase === 'idle') break
      await page.waitForTimeout(500)
    } while (Date.now() < deadline)
    assert.equal(result.runtime.phase, 'idle')
    assert.equal(result.runtime.terminal?.status, 'completed', JSON.stringify(result.runtime.terminal))
    assert.equal(readFileSync(join(output, 'workspace/result.txt'), 'utf8'), 'ELECTRON_PIPE_FIXTURE_20260925\n')
    const codeBlock = page.locator('.code-block').filter({ hasText: 'ELECTRON_PIPE_OK' }).last()
    const code = codeBlock.locator('pre code')
    await code.waitFor()
    const frames = [...beforeReload, ...await page.evaluate(() => window.__frames)]
    assert.ok(frames.some(frame => frame.type === 'turn_event' && frame.payload.method === 'item/agentMessage/delta'))
    writeFileSync(join(output, 'stream.json'), JSON.stringify(frames, null, 2))
    writeFileSync(join(output, 'session-read.json'), JSON.stringify(result, null, 2))
    await page.screenshot({ path: join(output, 'completed.png') })
    record('real-model-stream-and-persistence', { sessionId, frames: frames.length, terminal: result.runtime.terminal })
    await codeBlock.getByRole('button', { name: '复制代码', exact: true }).click()
    assert.equal((await app.evaluate(({ clipboard }) => clipboard.readText())).trim(), (await code.innerText()).trim())
    record('clipboard', true)
  }
  if (process.env.SINGULARITY_E2E_EXTENDED === '1') {
    await page.getByRole('button', { name: '展开任务工具', exact: true }).click()
    await page.getByRole('button', { name: '设置', exact: true }).click()
    await page.getByRole('button', { name: /B\.AI.*API 密钥已配置/ }).click()
    const providerForm = page.locator('.sg-editor').filter({ has: page.getByPlaceholder('bai', { exact: true }) })
    await providerForm.getByLabel('显示名称', { exact: true }).fill('B.AI Desktop E2E')
    await providerForm.getByRole('button', { name: '保存', exact: true }).click()
    assert.equal((await rpc('app.bootstrap')).modelCatalog.providers.find(provider => provider.providerId === 'bai').displayName, 'B.AI Desktop E2E')
    await page.getByRole('button', { name: '关闭设置', exact: true }).click()
    record('provider-settings-save', true)
    await page.locator('.session-row.is-selected').hover()
    await page.locator('.session-row.is-selected').getByRole('button', { name: '任务菜单', exact: true }).click()
    await page.getByRole('menuitem', { name: '重命名', exact: true }).click()
    await page.getByRole('textbox', { name: '名称', exact: true }).fill('Desktop E2E')
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await page.waitForTimeout(300)
    await page.reload()
    await page.getByText('Desktop E2E', { exact: true }).first().waitFor()
    record('session-rename-persist', true)
    if (process.env.SINGULARITY_E2E_CANCEL === '1') {
      await textarea.fill('请先实际执行 bash 的 sleep 60，再回复 DONE。这是停止操作验证。')
      await page.getByRole('button', { name: '发送消息', exact: true }).click()
      await page.getByRole('button', { name: '停止当前任务', exact: true }).waitFor()
      await page.waitForTimeout(2000)
      await page.getByRole('button', { name: '停止当前任务', exact: true }).click()
      await page.getByRole('button', { name: '发送消息', exact: true }).waitFor({ timeout: 30_000 })
      const selection = await page.evaluate(() => JSON.parse(localStorage.getItem('singularity.app.view.v1')))
      const result = await rpc('session.read', { workspaceId: workspace.workspaceId, sessionId: selection.selectedSessionId, limit: 40, beforeTurn: null })
      assert.equal(result.runtime.phase, 'idle')
      assert.equal(result.runtime.terminal.status, 'interrupted')
      record('model-cancel', result.runtime.terminal)
    }
    await page.locator('.session-row.is-selected').hover()
    await page.locator('.session-row.is-selected').getByRole('button', { name: '任务菜单', exact: true }).click()
    await page.getByRole('menuitem', { name: '归档任务', exact: true }).click()
    await page.waitForTimeout(400)
    assert.ok(!(await rpc('app.bootstrap')).sessionsByWorkspace[workspace.workspaceId].some(item => item.title === 'Desktop E2E'))
    record('session-archive', true)
  }
  record('errors', errors)
  assert.deepEqual(errors, [])
} catch (error) {
  const page = app.windows()[0]
  if (page) { await page.screenshot({ path: join(output, 'failure.png') }); writeFileSync(join(output, 'failure.txt'), await page.locator('body').innerText()) }
  throw error
} finally {
  writeFileSync(join(output, 'smoke.json'), JSON.stringify({ checks, errors }, null, 2))
  await app.close()
}
