//! 按实际 RPC DTO 确定性生成的客户端声明；任何声明都不带版本字段，
//! 握手版本另行作为常量导出，值取自 `PROTOCOL_VERSION`。

use std::{
    any::TypeId,
    collections::{BTreeMap, HashSet},
};
use ts_rs::{Config, TS, TypeVisitor};

pub(crate) struct Bindings {
    config: Config,
    declarations: BTreeMap<String, String>,
    visited: HashSet<TypeId>,
    extra: Vec<String>,
}

impl Bindings {
    pub(crate) fn config(&self) -> &Config {
        &self.config
    }

    pub(crate) fn add<T: TS + 'static + ?Sized>(&mut self) {
        if !self.visited.insert(TypeId::of::<T>()) {
            return;
        }
        T::visit_generics(self);
        if T::output_path().is_some() {
            let name = T::ident(&self.config);
            if !self.declarations.contains_key(&name) {
                self.declarations
                    .insert(name, format!("export {}", T::decl(&self.config)));
                T::visit_dependencies(self);
            }
        } else {
            T::visit_dependencies(self);
        }
    }

    pub(crate) fn push(&mut self, declaration: String) {
        self.extra.push(declaration);
    }
}

impl TypeVisitor for Bindings {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        self.add::<T>();
    }
}

/// wire DTO 的数值按 JSON number 导出。
pub fn client_types() -> String {
    let mut bindings = Bindings {
        config: Config::default().with_large_int("number"),
        declarations: BTreeMap::new(),
        visited: HashSet::new(),
        extra: Vec::new(),
    };
    crate::rpc::export_rpc_types(&mut bindings);
    bindings.add::<crate::StreamEnvelope>();
    bindings.add::<crate::TurnEvent>();
    bindings.add::<crate::RpcResponse>();
    bindings.add::<crate::ModelRequestSnapshot>();
    let mut output = String::from(
        "// Generated by singularity_protocol; cargo run -p singularity_protocol --features typescript --example export_types\n\n",
    );
    output.push_str(
        &bindings
            .declarations
            .into_values()
            .collect::<Vec<_>>()
            .join("\n\n"),
    );
    output.push_str("\n\n");
    output.push_str(&bindings.extra.join("\n\n"));
    output.push_str(&format!(
        "\n\n/** 握手版本，取自 Rust 的 PROTOCOL_VERSION。 */\nexport const protocolVersion = {} as const\n",
        crate::PROTOCOL_VERSION
    ));
    // ts_rs 可能在折行声明上留下行尾空格。
    let mut normalized = output
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    normalized.push('\n');
    normalized
}
