[package]
name = "singularity_app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[[bin]]
name = "singularity"
path = "src/main.rs"

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
singularity_core = { path = "../core" }
singularity_model = { path = "../model" }
singularity_protocol = { path = "../protocol" }
singularity_runtime = { path = "../runtime" }
thiserror.workspace = true
uuid.workspace = true
tokio.workspace = true
tokio-util.workspace = true
