// Generated by singularity_protocol; cargo run -p singularity_protocol --features typescript --example export_types

export type ActiveCompactionSnapshot = { startedAt: string, };

export type ActiveTurnRuntimeSnapshot = { turnId: string, };

export type AppBootstrap = {
/**
 * 系统用户主目录，用于界面缩短路径；与应用数据目录无关。
 */
userHome: string | null, sessionPhases: { [key in string]: SessionPhase }, revision: number, workspaces: Array<Workspace>, sessionsByWorkspace: { [key in string]: Array<ThreadSummary> }, modelCatalog: RedactedModelCatalog, };

export type DiagnosticSeverity = "info" | "warning" | "error";

export type DirectoryPickResult = { path: string | null, };

export type DiscoverModelsParams = { providerId: string, baseUrl: string, apiKey?: string | null, apiProtocol: string, };

export type DiscoveredModel = { modelId: string, displayName: string | null, maxContextTokens: number | null, maxOutputTokens: number | null, reasoningVariants: Array<ReasoningVariant>, defaultVariant: string | null, requiresReasoningContentForToolCalls: boolean | null,
/**
 * 元数据的补充来源；缺省表示仅使用提供方模型目录。
 */
metadataSource: string | null, };

export type EmptyParams = Record<string, never>;

export type FileCandidate = { path: string, };

export type FileSearchParams = { workspaceId: string, query: string, limit: number, };

export type HistoryItem = { "type": "request", startedAt?: string, observation: RequestObservation, } | { "type": "message", id: string, role: string, text: string, images?: Array<ImageAttachment>, } | { "type": "thinking", id: string, text: string, } | { "type": "tool_call", id: string, name: string, args: JsonValue, } | { "type": "tool_result", id: string, output: string, images?: Array<ImageAttachment>,
/**
 * read 工具真实读到的来源范围；其他工具和旧记录没有这个字段。
 */
readSource?: ReadSource, isError: boolean, durationMs?: number, } | { "type": "settings", id: string, provider: string, model: string, reasoning: string | null, } | { "type": "compaction", id: string, summary: string, } | { "type": "compaction_result", id: string, status: TurnStatus, message: string | null, };

export type ImageAttachment = { id: string, name: string, mimeType: string, width: number, height: number, };

export type ImageUpload = { name: string, dataUrl: string, };

export type ItemRef = { itemId: string, };

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null;

export type McpInspectParams = { serverId: string, workspaceId: string | null, reconnect: boolean, };

export type McpInspection = { serverId: string, connected: boolean, error: string | null, tools: Array<McpToolInfo>, };

export type McpSaveParams = { server: McpServerInput, };

export type McpServerInput = { serverId: string, enabled: boolean, startupTimeoutSec: number, toolTimeoutSec: number, transport: McpTransportInput, };

export type McpServerParams = { serverId: string, };

export type McpToggleParams = { serverId: string, enabled: boolean, };

export type McpToolInfo = { name: string, description: string, };

export type McpTransportInput = { "type": "stdio", command: string, args: Array<string>, cwd: string | null, env: { [key in string]: string }, } | { "type": "http", url: string, headers: { [key in string]: string }, };

export type ModelConfigurationField = "displayName" | "maxContextTokens" | "maxOutputTokens" | "reasoningVariants" | "thinkingWireFormat" | "chatOutputTokensField" | "requiresReasoningContentForToolCalls";

export type ModelConfigurationInput = { modelId: string,
/**
 * 智能配置管理的字段；None 表示未记录归属，编辑器仅补齐空字段。空列表为全手动。
 */
automaticFields: Array<ModelConfigurationField> | null, displayName: string | null, apiProtocol: string | null, maxContextTokens: number | null, maxOutputTokens: number | null, reasoningVariants: Array<ReasoningVariant> | null, defaultVariant: string | null, thinkingWireFormat: string | null,
/**
 * Chat 输出上限使用的 wire 字段名；`None` 表示发送 `max_tokens`。
 */
chatOutputTokensField: string | null, requiresReasoningContentForToolCalls: boolean | null, };

export type ModelRequestSnapshot = { definitionsId: string, messages: Array<RequestMessage>, tools: Array<RequestTool>, modelPreferences: RequestPreferences, };

export type PendingInput = { controlId: string, text: string, images?: Array<ImageAttachment>, };

export type PendingQuestion = {
/**
 * 工具条目身份；用于拒绝已经结束或属于另一轮的问题答案。
 */
itemId: string, questions: Array<UserQuestion>, };

export type ProviderAttemptStatus = "started" | "ok" | "error" | "cancelled";

export type ProviderConfigurationInput = { apiProtocol: string | null, providerId: string, displayName: string | null, baseUrl: string, models: Array<ModelConfigurationInput>, };

export type ProviderParams = { providerId: string, };

export type ProviderSaveParams = { provider: ProviderConfigurationInput,
/**
 * 只在写入时使用的新密钥；省略表示保留已有密钥。
 */
apiKey?: string, };

export type QuestionAnswerParams = { sessionId: string, itemId: string, answers: Array<UserQuestionAnswer>, };

export type QueueControlParams = { sessionId: string, controlId: string, };

export type QueuedInputDraft = { text: string, skills?: { [key in string]: string }, images: Array<ImageUpload>, };

export type ReadSource = {
/**
 * 实际读到的首个源文件行号；offset 省略或为 0 时规范化为 1。
 */
startLine: number,
/**
 * 正文行数；分页续读和超长单行的说明都不计入。
 */
lineCount: number, };

export type ReasoningVariant = { id: string, wireEffort: string | null, };

export type RedactedModelCatalog = {
/**
 * 配置读取或默认模型选择校验失败；尚未配置提供方或模型时为空。
 */
error: string | null, defaultSelector: string | null, providers: Array<RedactedProvider>, };

export type RedactedProvider = { apiProtocol: string | null, providerId: string, displayName: string | null, baseUrl: string, credentialConfigured: boolean, models: Array<ModelConfigurationInput>, };

export type RequestMessage = { role: string, content: string, };

export type RequestObservation = {
/**
 * 查找请求详情并配对开始、结束观测的键；每次 provider attempt 生成一个，
 * 与 assistant 或 compaction 的会话条目身份无关。
 */
requestId: string,
/**
 * 请求前缀的检查投影：完整指令、工具和偏好，不包含对话历史。
 */
requestHead?: ModelRequestSnapshot, purpose: RequestPurpose, attempt: number, provider: string, model: string, status: ProviderAttemptStatus, durationMs: number,
/**
 * 请求开始到首个生成增量的实测耗时；旧记录未采集时保持未知。
 */
ttftMs?: number,
/**
 * 首个生成增量到请求完成的耗时；旧记录未采集时保持未知。
 */
decodeMs?: number,
/**
 * 供应商上报总量，缺失时由已知输入输出相加得到。
 */
totalTokens?: number, inputTokens: number | null, outputTokens: number | null, cachedInputTokens: number | null, error: string | null,
/**
 * 这次 attempt 的稳定诊断码：它和 `error` 类别一起构成可以持久回放的失败
 * 事实，实时事件和历史读取都从这一份记录派生。
 */
diagnosticCode?: string, };

export type RequestPreferences = { maxOutputTokens: number | null, };

export type RequestPurpose = "generation" | "compaction";

export type RequestTool = { name: string, description: string, parametersSchema: JsonValue, };

export type RpcError = { code: RpcErrorCode, message: string, recovery: string, };

export type RpcErrorCode = "invalid_request" | "workspace_not_found" | "workspace_busy" | "session_not_found" | "session_busy" | "control_not_found" | "configuration_invalid" | "configuration_partially_saved" | "provider_unavailable" | "internal";

export type RpcResponse = { "type": "success", result: JsonValue, } | { "type": "error", error: RpcError, };

export type SessionImageParams = { sessionId: string, imageId: string, };

export type SessionModelUsage = {
/**
 * 有首 token 计时的请求：等待耗时合计与样本数，用于计算 TTFT；不依赖 usage 上报。
 */
ttftMs: number, ttftRequests: number,
/**
 * 输入合计（包含命中缓存的那部分）。
 */
inputTokens: number,
/**
 * 已知的缓存输入合计；仅 cache_usage_complete 为真时可计算命中率。
 */
cachedInputTokens: number, outputTokens: number, totalTokens: number,
/**
 * 同时具有生成耗时和输出计数的样本，用于计算 TPS。
 */
decodeTokens: number, decodeMs: number,
/**
 * 计入合计的请求是否都明确报告了缓存输入用量。
 */
cacheUsageComplete: boolean,
/**
 * 计入统计的请求耗时合计（毫秒），含等待首个 token。
 */
generationMs: number,
/**
 * 是否有请求报告了 usage；为 false 时 token 计数不含任何真实消费。
 */
usagePresent: boolean, };

export type SessionParams = { sessionId: string, };

export type SessionPhase = "idle" | "reserved" | "running" | "compacting" | "stopping";

export type SessionReadParams = { sessionId: string, beforeTurn?: string | null, limit: number, };

export type SessionReadResult = { history: ThreadReadPage, runtime: SessionRuntime, activeEvents: Array<TurnEventEnvelope>, };

export type SessionRenameParams = { sessionId: string, name: string, };

export type SessionRuntime = { sessionRevision: number, phase: SessionPhase, selector: string | null, modelContextWindow: number | null, pendingInput: PendingInput | null, pendingQuestion: PendingQuestion | null, activeTurn: ActiveTurnRuntimeSnapshot | null, activeCompaction: ActiveCompactionSnapshot | null, terminal: SessionTerminalSnapshot | null, };

export type SessionTerminalSnapshot = { source: SessionTerminalSource, status: TurnStatus,
/**
 * 该回合的中断来自已接受的用户停止，与持久化摘要使用同一事实。
 */
manuallyStopped: boolean, message: string | null, };

export type SessionTerminalSource = "turn" | "compaction";

export type SessionTextParams = { sessionId: string, text: string,
/**
 * 用户选择的技能名到绝对文件路径的绑定。
 */
skills?: { [key in string]: string }, images?: Array<ImageUpload>, };

export type SkillCatalog = { skills: Array<SkillMetadata>, diagnostics: Array<string>, };

export type SkillMetadata = { name: string, description: string, path: string, };

export type StreamEnvelope = { revision: number, } & ({ "type": "ready" } | { "type": "app_changed", payload: AppBootstrap, } | { "type": "session_changed", sessionId: string, payload: SessionRuntime, } | { "type": "turn_event", sessionId: string, payload: TurnEventEnvelope, } | { "type": "session_settled", sessionId: string, payload: SessionRuntime, } | { "type": "resync_required" });

export type ThreadReadPage = { summary: ThreadSummary, turns: Array<ThreadTurn>, nextCursor: string | null, };

export type ThreadSummary = { threadId: string, cwd: string, createdAt: string, updatedAt: string, title: string | null, status: TurnStatus | null,
/**
 * 最近一次被中断的 run，在账本里有明确的用户取消记录。
 */
manuallyStopped: boolean, turnCount: number,
/**
 * 整份账本的累计模型用量。它只在生成快照时更新，运行中回合的增量由调用方
 * 从活动事件里另算（读盘的冻结窗口保证两者不重叠），所以这里不是实时值。
 */
usage: SessionModelUsage, };

export type ThreadTurn = {
/**
 * 本轮 run operation 的持久化边界时间；前导组或缺失边界为 None。
 */
startedAt?: string, finishedAt?: string, turnId: string | null,
/**
 * 该轮的终态；只有开始标记、还没结束的轮是 running（崩溃遗留的会被整体
 * 状态投影修正为 interrupted），前导组是 null。
 */
status: TurnStatus | null,
/**
 * 该轮失败终态落盘下来的细节；成功、中断、前导组，以及没记录细节的旧日志都是 None。
 * 它和实时的 `turn/error` 事件表达同一个概念，重读历史时不依赖 runtime 最近一次的错误文本。
 */
error?: TurnErrorDetail,
/**
 * 该轮的公开条目，按会话顺序排列。
 */
items: Array<HistoryItem>, };

export type Turn = { turnId: string, threadId: string, status: TurnStatus,
/**
 * provider usage 的投影（评估工具的数据来源）。provider 可能不报告 usage；缺失时本字段是
 * None，不把未知伪装成零。请求观测写入 JSONL，重启后可聚合历史用量。
 */
usage?: TurnModelUsage, };

export type TurnErrorDetail = { cause: TurnFailureCause, message: string, };

export type TurnEventEnvelope = { sessionRevision: number, } & ({ "method": "turn/started", "params": { turn: Turn, startedAt: string, } } | { "method": "turn/userMessage", "params": { threadId: string, turnId: string, item: ItemRef, text: string, images?: Array<ImageAttachment>, } } | { "method": "item/started", "params": { threadId: string, turnId: string, item: ItemRef, } } | { "method": "item/agentMessage/delta", "params": { threadId: string, turnId: string, item: ItemRef, delta: string, } } | { "method": "item/agentThinking/delta", "params": { threadId: string, turnId: string, item: ItemRef, delta: string, } } | { "method": "tool/execution/start", "params": { threadId: string, turnId: string,
/**
 * 与历史共享的公开 occurrence 身份，不是 provider 在 wire 上的调用 ID。
 */
item: ItemRef, toolName: string, args: JsonValue, startedAt: string, } } | { "method": "tool/execution/update", "params": { threadId: string, turnId: string, item: ItemRef, partialResult: string, } } | { "method": "tool/execution/end", "params": { threadId: string, turnId: string, item: ItemRef, output: string, images?: Array<ImageAttachment>, isError: boolean, durationMs?: number,
/**
 * read 工具真实读到的来源范围；其他工具和旧记录没有这个字段。
 */
readSource?: ReadSource, } } | { "method": "item/discarded", "params": { threadId: string, turnId: string, item: ItemRef, } } | { "method": "item/completed", "params": { threadId: string, turnId: string, item: ItemRef, content?: HistoryItem, } } | { "method": "item/failed", "params": { threadId: string, turnId: string, item: ItemRef, content?: HistoryItem, error: string, } } | { "method": "agent/diagnostic", "params": { threadId: string,
/**
 * 独立压缩不属于回合；普通执行使用实际回合身份。
 */
turnId: string | null, severity: DiagnosticSeverity, code: string, message: string, } } | { "method": "provider/attempt", "params": { observation: RequestObservation, threadId: string,
/**
 * 独立压缩不属于回合；普通执行使用实际回合身份。
 */
turnId: string | null, } } | { "method": "turn/completed", "params": { turn: Turn, finishedAt: string, } } | { "method": "turn/controlChanged", "params": Record<symbol, never> } | { "method": "turn/error", "params": { threadId: string, turnId: string, error: TurnErrorDetail, finishedAt: string, } });

export type TurnFailureCause = "store" | "project_instructions" | "workspace" | "provider_rate_limited" | "provider_network" | "provider_timeout" | "provider_auth" | "provider_validation" | "provider_overloaded" | "provider_cancelled" | "provider_context_overflow" | "provider_unknown" | "internal";

export type TurnModelUsage = { inputTokens: number, outputTokens: number, totalTokens: number, cachedInputTokens: number, reasoningTokens: number,
/**
 * 这次聚合里是否至少有一个请求完整上报了输入和输出计数（两项都齐全）。
 * 为 false 时各个计数保持「未知」的含义，不把缺失伪装成零消费或可计算的金额。
 */
usagePresent: boolean, };

export type TurnStatus = "running" | "completed" | "failed" | "interrupted";

export type UpdateSettingsParams = { sessionId: string, selector: string, };

export type UserQuestion = { id: string, question: string, options: Array<UserQuestionOption>, multiSelect: boolean, };

export type UserQuestionAnswer = { id: string, selected: Array<string>, text: string, skipped: boolean, };

export type UserQuestionOption = { label: string, description: string | null, };

export type Workspace = { workspaceId: string, name: string, root: string, };

export type WorkspaceAddParams = { root: string, };

export type WorkspaceParams = { workspaceId: string, };

export type WorkspaceRemoveParams = { workspaceId: string, draftSessionIds: Array<string>, };

export type WorkspaceRenameParams = { workspaceId: string, name: string, };

export interface RpcContract {
  "app.bootstrap": { params: EmptyParams; result: AppBootstrap }
  "directory.pick": { params: EmptyParams; result: DirectoryPickResult }
  "file.search": { params: FileSearchParams; result: Array<FileCandidate> }
  "skills.list": { params: WorkspaceParams; result: SkillCatalog }
  "workspace.add": { params: WorkspaceAddParams; result: Workspace }
  "workspace.remove": { params: WorkspaceRemoveParams; result: Array<string> }
  "workspace.rename": { params: WorkspaceRenameParams; result: null }
  "model.saveProvider": { params: ProviderSaveParams; result: null }
  "model.discover": { params: DiscoverModelsParams; result: Array<DiscoveredModel> }
  "model.removeProvider": { params: ProviderParams; result: null }
  "mcp.list": { params: EmptyParams; result: Array<McpServerInput> }
  "mcp.save": { params: McpSaveParams; result: null }
  "mcp.remove": { params: McpServerParams; result: null }
  "mcp.toggle": { params: McpToggleParams; result: null }
  "mcp.inspect": { params: McpInspectParams; result: McpInspection }
  "session.create": { params: WorkspaceParams; result: SessionReadResult }
  "session.read": { params: SessionReadParams; result: SessionReadResult }
  "session.imageRead": { params: SessionImageParams; result: string }
  "session.rename": { params: SessionRenameParams; result: null }
  "session.archive": { params: SessionParams; result: null }
  "session.submit": { params: SessionTextParams; result: null }
  "session.steer": { params: SessionTextParams; result: null }
  "session.followUp": { params: SessionTextParams; result: null }
  "session.queueWithdraw": { params: QueueControlParams; result: null }
  "session.queueEdit": { params: QueueControlParams; result: QueuedInputDraft }
  "session.queueSendNow": { params: QueueControlParams; result: null }
  "session.answerQuestion": { params: QuestionAnswerParams; result: null }
  "session.abort": { params: SessionParams; result: null }
  "session.compact": { params: SessionParams; result: null }
  "session.updateSettings": { params: UpdateSettingsParams; result: null }
}

export const modelConfigurationFields = ["displayName","maxContextTokens","maxOutputTokens","reasoningVariants","thinkingWireFormat","chatOutputTokensField","requiresReasoningContentForToolCalls"] as const
