[package]
name = "singularity_sandbox"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
cap-fs-ext.workspace = true
cap-std.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
singularity_core = { path = "../core" }

[target.'cfg(windows)'.dependencies]
dunce = "1.0"
singularity_windows_sandbox = { path = "../windows-sandbox" }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile.workspace = true
