// Generated by singularity_protocol; cargo run -p singularity_protocol --features typescript --example export_types

type StampedTurnEvent<E> = E extends { method: infer M; params: infer P } ? { sessionRevision: number; method: M; params: M extends 'turn/started' | 'tool/execution/start' ? Omit<P, 'startedAt'> & { startedAt: string } : P } : never;

export type ActionReceipt = { requestId: string, accepted: boolean, generation: string, revision: number, sessionId: string | null, turnId: string | null, control: ControlSnapshot | null, };

export type ActiveCompactionSnapshot = { startedAt: string, };

export type ActiveTurnSnapshot = { turnId: string, events: Array<WorkbenchTurnEvent>, startedAt: string, };

export type ApiKeyParams = { providerId: string, apiKey: string, };

export type ContentText = { type: "text", text: string, };

export type ControlChannel = "steer" | "follow_up" | "cancel";

export type ControlDisposition = "pending" | "injected" | "started_as_new_turn" | "cancelled";

export type ControlSnapshot = { controlId: string, turnId: string, channel: ControlChannel, sequence: number, text: string | null, disposition: ControlDisposition, };

export type CredentialConfigured = { providerId: string, credentialConfigured: boolean, };

export type DiagnosticSeverity = "info" | "warning" | "error";

export type DirectoryEntry = { name: string, path: string, kind: DirectoryEntryKind, };

export type DirectoryEntryKind = "root" | "parent" | "directory" | "file";

export type DirectoryListParams = { path?: string | null, };

export type DirectoryPickResult = { native: boolean, path: string | null, };

export type DiscoverModelsParams = { providerId: string, baseUrl: string, apiKey?: string | null, };

export type DiscoveredModel = { modelId: string, displayName: string | null, maxContextTokens: number | null, maxOutputTokens: number | null, reasoningVariants: Array<ReasoningVariantInput>, defaultVariant: string | null, thinkingWireFormat: string | null, };

export type EmptyParams = Record<string, never>;

export type EndpointSnapshot = { authority: string, };

export type FileCandidate = { path: string, kind: DirectoryEntryKind, };

export type FileSearchParams = { workspaceId: string, sessionId?: string | null, query: string, limit: number, };

export type HistoryItem = { "type": "request", id: string, timestamp: string, observation: RequestObservation, } | { "type": "message", id: string, role: string, text: string, } | { "type": "thinking", id: string, text: string, } | { "type": "tool_call", id: string, name: string, args: JsonValue, } | { "type": "tool_result", id: string, output: string, diff?: string, isError: boolean, durationMs?: number, } | { "type": "settings", id: string, provider: string, model: string, reasoning: string | null, } | { "type": "compaction", id: string, summary: string, };

export type ItemRef = { itemId: string, };

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null;

export type ModelConfigurationStatus = "ready" | "missing" | "invalid";

export type ModelRequestSnapshot = { request_id: string, messages: Array<RequestMessage>, tools: Array<RequestTool>, model_preferences: RequestPreferences, };

export type ProviderApiProtocol = "chat" | "responses";

export type ProviderAttemptStatus = "started" | "ok" | "error" | "cancelled";

export type ProviderConfigurationInput = { providerId: string, displayName: string | null, baseUrl: string, models: Array<ProviderModelInput>, makeDefault: boolean, };

export type ProviderModelInput = { modelId: string, displayName: string | null, apiProtocol: ProviderApiProtocol, maxContextTokens: number | null, maxOutputTokens: number | null, reasoningVariants: Array<ReasoningVariantInput>, defaultVariant: string | null, thinkingWireFormat: string | null, };

export type ProviderParams = { providerId: string, };

export type ProviderSaveParams = { provider: ProviderConfigurationInput, };

export type QueueControlParams = { workspaceId: string, sessionId: string, controlId: string, };

export type QueueReplaceParams = { workspaceId: string, sessionId: string, controlId: string, text: string, };

export type ReasoningVariantInput = { id: string, enabled: boolean, wireEffort: string | null, };

export type RedactedModel = { modelId: string, displayName: string | null, apiProtocol: string, maxContextTokens: number | null, maxOutputTokens: number | null, reasoningVariants: Array<RedactedReasoningVariant>, defaultVariant: string | null, thinkingWireFormat: string | null, };

export type RedactedModelCatalog = { configuration: ModelConfigurationStatus, message: string | null, defaultSelector: string | null, providers: Array<RedactedProvider>, presets: Array<ProviderConfigurationInput>, };

export type RedactedProvider = { providerId: string, displayName: string | null, baseUrl: string, credentialConfigured: boolean, models: Array<RedactedModel>, };

export type RedactedReasoningVariant = { id: string, enabled: boolean, wireEffort: string | null, };

export type RequestMessage = { role: string, content: string, tool_call_id: string | null, tool_calls?: Array<JsonValue>, };

export type RequestObservation = { 
/**
 * Lookup key for immutable request details. Legacy records use their ledger entry ID.
 */
requestId: string, 
/**
 * Small display projection: only system/developer messages, tools and preferences.
 */
requestHead?: ModelRequestSnapshot, purpose: RequestPurpose, ordinal: number, attempt: number, provider: string, model: string, status: ProviderAttemptStatus, durationMs: number, inputTokens: number | null, outputTokens: number | null, cachedInputTokens: number | null, error: string | null, request?: ModelRequestSnapshot, 
/**
 * Inspection failure; does not change the provider outcome or session recoverability.
 */
requestError?: string, };

export type RequestPreferences = { model_name: string | null, max_output_tokens: number | null, };

export type RequestPurpose = "generation" | "compaction";

export type RequestTool = { name: string, description: string, parameters_schema: JsonValue, };

export type ResyncRequiredPayload = { reason: string, };

export type RetryAfterSource = "provider_header";

export type RpcError = { code: RpcErrorCode, message: string, recovery: string, preservedInput?: string, };

export type RpcErrorCode = "invalid_request" | "workspace_not_found" | "workspace_busy" | "session_not_found" | "session_busy" | "control_not_found" | "configuration_invalid" | "provider_unavailable" | "conflict" | "internal";

export type RpcResponse = { version: number, requestId: string, ok: boolean, generation: string, revision: number, result?: JsonValue, error?: RpcError, };

export type SessionArchived = { archived: boolean, };

export type SessionCreateParams = { workspaceId: string, settings?: SessionSettingsInput | null, };

export type SessionParams = { workspaceId: string, sessionId: string, };

export type SessionPhase = "idle" | "reserved" | "running" | "compacting" | "stopping";

export type SessionReadParams = { workspaceId: string, sessionId: string, beforeTurn?: string | null, limit: number, };

export type SessionReadResult = { summary: ThreadSummary, history: ThreadReadPage, runtime: SessionSnapshot, };

export type SessionRenameParams = { workspaceId: string, sessionId: string, name: string, };

export type SessionRequestParams = { workspaceId: string, sessionId: string, requestId: string, };

export type SessionSettingsInput = { selector?: string | null, };

export type SessionSettledPayload = { runtime: SessionSnapshot, };

export type SessionSnapshot = { sessionRevision: number, phase: SessionPhase, selector: string | null, 
/**
 * durable control ledger 的完整归约投影，按接受 sequence 排序。
 */
controls: Array<ControlSnapshot>, 
/**
 * 当前仍位于 follow-up 队列中的控制；立即提升后会从这里消失，但其
 * lifecycle 仍保留在 controls 中直至终态 disposition 落盘。
 */
pendingControls: Array<ControlSnapshot>, activeTurn: ActiveTurnSnapshot | null, activeCompaction: ActiveCompactionSnapshot | null, terminal: SessionTerminalSnapshot | null, };

export type SessionTerminalSnapshot = { status: TurnStatus, message: string | null, };

export type SessionTextParams = { workspaceId: string, sessionId: string, text: string, };

export type SkillCatalog = { skills: Array<SkillMetadata>, diagnostics: Array<string>, };

export type SkillMetadata = { name: string, description: string, path: string, userInvocable: boolean, disableModelInvocation: boolean, };

export type SkillsListParams = { workspaceId: string, sessionId?: string | null, };

export type StreamEnvelope = { version: number, generation: string, revision: number, } & ({ "type": "ready", payload: EmptyParams, } | { "type": "workbench_changed", payload: WorkbenchBootstrap, } | { "type": "session_changed", sessionId: string, payload: SessionSnapshot, } | { "type": "turn_event", sessionId: string, payload: WorkbenchTurnEvent, } | { "type": "session_settled", sessionId: string, payload: SessionSettledPayload, } | { "type": "resync_required", payload: ResyncRequiredPayload, });

export type ThreadReadPage = { summary: ThreadSummary, compactionSummary: string | null, turns: Array<ThreadTurn>, nextCursor: string | null, };

export type ThreadSummary = { threadId: string, cwd: string, createdAt: string, updatedAt: string, title: string | null, model: string | null, status: TurnStatus | null, 
/**
 * The latest interrupted run has an explicit user cancellation in the ledger.
 */
manuallyStopped: boolean, turnCount: number, totalTokens: number, };

export type ThreadTurn = { turnId: string | null, 
/**
 * 该轮终态；仅有开始标记的未终止轮为 running（崩溃遗留会被整体状态
 * 投影修正为 interrupted），前导组为 null。
 */
status: TurnStatus | null, 
/**
 * 该轮公开条目，按会话顺序排列。
 */
items: Array<HistoryItem>, };

export type ToolResultPayload = { content: [ContentText], isError: boolean, 
/**
 * 文件变更独立于模型可见文本，供客户端直接解析和展示。
 */
diff?: string, };

export type Turn = { turnId: string, threadId: string, status: TurnStatus, 
/**
 * provider usage 投影（评估工具数据源）。
 *
 * provider 可能不报告 usage；缺失时本字段为 None，不把未知伪装成零。
 * 终态 usage 同时写入 JSONL metadata，重启后可从公开历史恢复。
 */
usage?: TurnModelUsage, };

export type TurnErrorDetail = { stage: TurnFailureStage, cause: TurnFailureCause, message: string, };

export type TurnEvent = { "method": "turn/started", "params": { turn: Turn, } } | { "method": "turn/userMessage", "params": { threadId: string, turnId: string, entryId: string, text: string, } } | { "method": "item/started", "params": { threadId: string, turnId: string, item: ItemRef, } } | { "method": "item/agentMessage/delta", "params": { threadId: string, turnId: string, item: ItemRef, delta: string, } } | { "method": "item/agentThinking", "params": { threadId: string, turnId: string, item: ItemRef, text: string, } } | { "method": "item/agentThinking/delta", "params": { threadId: string, turnId: string, item: ItemRef, delta: string, } } | { "method": "tool/execution/start", "params": { threadId: string, turnId: string, 
/**
 * Public occurrence ID shared with history, distinct from the provider's wire ID.
 */
toolCallId: string, toolName: string, args: JsonValue, startedAt?: string, } } | { "method": "tool/execution/update", "params": { threadId: string, turnId: string, toolCallId: string, toolName: string, args: JsonValue, partialResult: string, } } | { "method": "tool/execution/end", "params": { threadId: string, turnId: string, toolCallId: string, toolName: string, result: ToolResultPayload, durationMs?: number, } } | { "method": "item/completed", "params": { threadId: string, turnId: string, item: ItemRef, } } | { "method": "item/failed", "params": { threadId: string, turnId: string, item: ItemRef, error: string, } } | { "method": "agent/diagnostic", "params": { threadId: string, turnId: string, severity: DiagnosticSeverity, code: string, message: string, } } | { "method": "provider/attempt", "params": { requestId: string, requestHead?: ModelRequestSnapshot, purpose: RequestPurpose, threadId: string, turnId: string, 
/**
 * 1-based provider request sequence within the current turn.
 */
attempt: number, modelTurnOrdinal: number, provider: string, model: string, protocol: string, status: ProviderAttemptStatus, attemptDurationMs: number | null, 
/**
 * Measured usage from this attempt; absent when the provider did not report it.
 */
inputTokens: number | null, outputTokens: number | null, cachedInputTokens: number | null, errorCategory: string | null, diagnosticCode: string | null, retryAfterMs: number | null, retryAfterSource: RetryAfterSource | null, } } | { "method": "turn/completed", "params": { turn: Turn, } } | { "method": "turn/controlChanged", "params": { control: ControlSnapshot, } } | { "method": "turn/error", "params": { threadId: string, turnId: string, error: TurnErrorDetail, } };

export type TurnFailureCause = "store" | "project_instructions" | "workspace" | "provider_rate_limited" | "provider_network" | "provider_timeout" | "provider_auth" | "provider_validation" | "provider_overloaded" | "provider_cancelled" | "provider_context_overflow" | "provider_unknown" | "internal";

export type TurnFailureStage = "agent_loop" | "terminal_outcome";

export type TurnModelUsage = { inputTokens: number, outputTokens: number, totalTokens: number, cachedInputTokens: number, reasoningTokens: number, 
/**
 * 原始 usage 对象是否存在；为 false 时各计数保持 unknown 表示，不把缺失
 * 伪装成零消费或其它可计算金额。
 */
usagePresent: boolean, 
/**
 * 该聚合表示的每个 provider 请求是否都报告了精确 usage；未报告的末次
 * 请求 usage 保持 partial 而非表示为 0。
 */
usageComplete: boolean, };

export type TurnStatus = "running" | "completed" | "failed" | "interrupted";

export type UpdateSettingsParams = { workspaceId: string, sessionId: string, selector: string, };

export type WorkbenchBootstrap = { sessionPhases: { [key in string]: SessionPhase }, generation: string, revision: number, endpoint: EndpointSnapshot, workspaces: Array<Workspace>, sessionsByWorkspace: { [key in string]: Array<ThreadSummary> }, modelCatalog: RedactedModelCatalog, };

export type WorkbenchTurnEvent = StampedTurnEvent<TurnEvent>;

export type Workspace = { workspaceId: string, name: string, root: string, };

export type WorkspaceAddParams = { root: string, };

export type WorkspaceParams = { workspaceId: string, };

export type WorkspaceRemoved = { removed: boolean, };

export type WorkspaceRenameParams = { workspaceId: string, name: string, };

export interface RpcContract {
  "workbench.bootstrap": { params: EmptyParams; result: WorkbenchBootstrap }
  "directory.list": { params: DirectoryListParams; result: Array<DirectoryEntry> }
  "directory.pick": { params: EmptyParams; result: DirectoryPickResult }
  "file.search": { params: FileSearchParams; result: Array<FileCandidate> }
  "skills.list": { params: SkillsListParams; result: SkillCatalog }
  "workspace.add": { params: WorkspaceAddParams; result: Workspace }
  "workspace.remove": { params: WorkspaceParams; result: WorkspaceRemoved }
  "workspace.rename": { params: WorkspaceRenameParams; result: Workspace }
  "model.saveProvider": { params: ProviderSaveParams; result: RedactedModelCatalog }
  "model.setApiKey": { params: ApiKeyParams; result: CredentialConfigured }
  "model.discover": { params: DiscoverModelsParams; result: Array<DiscoveredModel> }
  "model.removeProvider": { params: ProviderParams; result: RedactedModelCatalog }
  "session.create": { params: SessionCreateParams; result: SessionReadResult }
  "session.read": { params: SessionReadParams; result: SessionReadResult }
  "session.request": { params: SessionRequestParams; result: ModelRequestSnapshot }
  "session.rename": { params: SessionRenameParams; result: ThreadSummary }
  "session.archive": { params: SessionParams; result: SessionArchived }
  "session.submit": { params: SessionTextParams; result: ActionReceipt }
  "session.steer": { params: SessionTextParams; result: ActionReceipt }
  "session.followUp": { params: SessionTextParams; result: ActionReceipt }
  "session.queueWithdraw": { params: QueueControlParams; result: ActionReceipt }
  "session.queueReplace": { params: QueueReplaceParams; result: ActionReceipt }
  "session.queueSendNow": { params: QueueControlParams; result: ActionReceipt }
  "session.abort": { params: SessionParams; result: ActionReceipt }
  "session.compact": { params: SessionParams; result: ActionReceipt }
  "session.updateSettings": { params: UpdateSettingsParams; result: ActionReceipt }
}
