// Generated by singularity_protocol; cargo run -p singularity_protocol --features typescript --example export_types

export type ActiveCompactionSnapshot = { startedAt: string, };

export type ActiveTurnRuntimeSnapshot = { turnId: string, startedAt: string, };

export type ApiKeyParams = { providerId: string, apiKey: string, };

export type ControlChannel = "steer" | "follow_up";

export type ControlDisposition = "pending" | "injected" | "started_as_new_turn" | "cancelled";

export type ControlSnapshot = { controlId: string, turnId: string, channel: ControlChannel, sequence: number, text: string, disposition: ControlDisposition, };

export type DiagnosticSeverity = "info" | "warning" | "error";

export type DirectoryPickResult = { path: string | null, };

export type DiscoverModelsParams = { providerId: string, baseUrl: string, apiKey?: string | null, };

export type DiscoveredModel = { modelId: string, displayName: string | null, maxContextTokens: number | null, maxOutputTokens: number | null, reasoningVariants: Array<ReasoningVariant>, defaultVariant: string | null, thinkingWireFormat: string | null, };

export type EmptyParams = Record<string, never>;

export type FileCandidate = { path: string, };

export type FileSearchParams = { workspaceId: string, sessionId?: string | null, query: string, limit: number, };

export type HistoryItem = { "type": "request", id: string, timestamp: string, observation: RequestObservation, } | { "type": "message", id: string, role: string, text: string, } | { "type": "thinking", id: string, text: string, } | { "type": "tool_call", id: string, name: string, args: JsonValue, } | { "type": "tool_result", id: string, output: string, diff?: string, isError: boolean, durationMs?: number, } | { "type": "settings", id: string, provider: string, model: string, reasoning: string | null, } | { "type": "compaction", id: string, summary: string, };

export type ItemRef = { itemId: string, };

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null;

export type ModelConfigurationInput = { modelId: string, displayName: string | null, apiProtocol: string | null, maxContextTokens: number | null, maxOutputTokens: number | null, reasoningVariants: Array<ReasoningVariant>, defaultVariant: string | null, thinkingWireFormat: string | null,
/**
 * Chat 输出上限的 wire 字段名；`None` 表示发送 `max_tokens`。表单不提供
 * 该开关的控件，但保存往返时原样保留既有取值。
 */
chatOutputTokensField: string | null, };

export type ModelConfigurationStatus = "ready" | "missing" | "invalid";

export type ModelRequestSnapshot = { requestId: string, messages: Array<RequestMessage>, tools: Array<RequestTool>, modelPreferences: RequestPreferences, };

export type ProviderAttemptStatus = "started" | "ok" | "error" | "cancelled";

export type ProviderConfigurationInput = { providerId: string, displayName: string | null, baseUrl: string, models: Array<ModelConfigurationInput>, };

export type ProviderParams = { providerId: string, };

export type ProviderSaveParams = { provider: ProviderConfigurationInput,
/**
 * 只写的新密钥；省略或空字符串表示保留已有密钥。
 */
apiKey?: string, };

export type QueueControlParams = { workspaceId: string, sessionId: string, controlId: string, };

export type QueueReplaceParams = { workspaceId: string, sessionId: string, controlId: string, text: string, };

export type ReasoningVariant = { id: string, enabled: boolean, wireEffort: string | null, };

export type RedactedModelCatalog = { configuration: ModelConfigurationStatus, message: string | null, defaultSelector: string | null, providers: Array<RedactedProvider>, };

export type RedactedProvider = { providerId: string, displayName: string | null, baseUrl: string, credentialConfigured: boolean, models: Array<ModelConfigurationInput>, };

export type RequestMessage = { role: string, content: string, };

export type RequestObservation = {
/**
 * 不可变请求详情的查找键；旧记录使用其账本条目 ID。
 */
requestId: string,
/**
 * 小幅显示投影：只含 system/developer 消息、工具与偏好。
 */
requestHead?: ModelRequestSnapshot, purpose: RequestPurpose, ordinal: number, attempt: number, provider: string, model: string, status: ProviderAttemptStatus, durationMs: number, inputTokens: number | null, outputTokens: number | null, cachedInputTokens: number | null, error: string | null,
/**
 * 检查失败；不改变 provider 结果与会话可恢复性。
 */
requestError?: string, };

export type RequestPreferences = { maxOutputTokens: number | null, };

export type RequestPurpose = "generation" | "compaction";

export type RequestTool = { name: string, description: string, parametersSchema: JsonValue, };

export type ResyncRequiredPayload = { reason: string, };

export type RetryAfterSource = "provider_header";

export type RpcError = { code: RpcErrorCode, message: string, recovery: string, };

export type RpcErrorCode = "invalid_request" | "workspace_not_found" | "workspace_busy" | "session_not_found" | "session_busy" | "control_not_found" | "configuration_invalid" | "configuration_partially_saved" | "provider_unavailable" | "conflict" | "internal";

export type RpcResponse = { version: number, requestId: string, ok: boolean, result?: JsonValue, error?: RpcError, };

export type SessionCreateParams = { workspaceId: string, settings?: SessionSettingsInput | null, };

export type SessionParams = { workspaceId: string, sessionId: string, };

export type SessionPhase = "idle" | "reserved" | "running" | "compacting" | "stopping";

export type SessionReadParams = { workspaceId: string, sessionId: string, beforeTurn?: string | null, limit: number, };

export type SessionReadResult = { history: ThreadReadPage, runtime: SessionRuntime, activeEvents: Array<WorkbenchTurnEvent>, };

export type SessionRenameParams = { workspaceId: string, sessionId: string, name: string, };

export type SessionRuntime = { sessionRevision: number, phase: SessionPhase, selector: string | null, modelContextWindow: number | null, pendingControls: Array<ControlSnapshot>, activeTurn: ActiveTurnRuntimeSnapshot | null, activeCompaction: ActiveCompactionSnapshot | null, terminal: SessionTerminalSnapshot | null, };

export type SessionSettingsInput = { selector?: string | null, };

export type SessionSettledPayload = { runtime: SessionRuntime, };

export type SessionTerminalSnapshot = { status: TurnStatus, message: string | null, };

export type SessionTextParams = { workspaceId: string, sessionId: string, text: string, };

export type SkillCatalog = { skills: Array<SkillMetadata>, diagnostics: Array<string>, };

export type SkillMetadata = { name: string, description: string, };

export type SkillsListParams = { workspaceId: string, sessionId?: string | null, };

export type StreamEnvelope = { version: number, generation: string, revision: number, } & ({ "type": "ready", payload: EmptyParams, } | { "type": "workbench_changed", payload: WorkbenchBootstrap, } | { "type": "session_changed", sessionId: string, payload: SessionRuntime, } | { "type": "turn_event", sessionId: string, payload: WorkbenchTurnEvent, } | { "type": "session_settled", sessionId: string, payload: SessionSettledPayload, } | { "type": "resync_required", payload: ResyncRequiredPayload, });

export type ThreadReadPage = { summary: ThreadSummary, turns: Array<ThreadTurn>, nextCursor: string | null, };

export type ThreadSummary = { threadId: string, cwd: string, createdAt: string, updatedAt: string, title: string | null, model: string | null, status: TurnStatus | null,
/**
 * 最近一次中断的 run 在账本里有明确的用户取消记录。
 */
manuallyStopped: boolean, turnCount: number, };

export type ThreadTurn = { turnId: string | null,
/**
 * 该轮终态；仅有开始标记的未终止轮为 running（崩溃遗留会被整体状态
 * 投影修正为 interrupted），前导组为 null。
 */
status: TurnStatus | null,
/**
 * 该轮公开条目，按会话顺序排列。
 */
items: Array<HistoryItem>, };

export type Turn = { turnId: string, threadId: string, status: TurnStatus,
/**
 * provider usage 投影（评估工具数据源）。
 *
 * provider 可能不报告 usage；缺失时本字段为 None，不把未知伪装成零。
 * 终态 usage 同时写入 JSONL metadata，重启后可从公开历史恢复。
 */
usage?: TurnModelUsage, };

export type TurnErrorDetail = { stage: TurnFailureStage, cause: TurnFailureCause, message: string, };

export type TurnEvent = { "method": "turn/started", "params": { turn: Turn, startedAt: string, } } | { "method": "turn/userMessage", "params": { threadId: string, turnId: string, item: ItemRef, text: string, } } | { "method": "item/started", "params": { threadId: string, turnId: string, item: ItemRef, } } | { "method": "item/agentMessage/delta", "params": { threadId: string, turnId: string, item: ItemRef, delta: string, } } | { "method": "item/agentThinking/delta", "params": { threadId: string, turnId: string, item: ItemRef, delta: string, } } | { "method": "tool/execution/start", "params": { threadId: string, turnId: string,
/**
 * 与历史共享的公开 occurrence 身份，不是 provider 的 wire 调用 ID。
 */
item: ItemRef, toolName: string, args: JsonValue, startedAt: string, } } | { "method": "tool/execution/update", "params": { threadId: string, turnId: string, item: ItemRef, partialResult: string, } } | { "method": "tool/execution/end", "params": { threadId: string, turnId: string, item: ItemRef, output: string, isError: boolean, diff?: string, durationMs?: number, } } | { "method": "item/completed", "params": { threadId: string, turnId: string, item: ItemRef, content?: HistoryItem, } } | { "method": "item/failed", "params": { threadId: string, turnId: string, item: ItemRef, content?: HistoryItem, error: string, } } | { "method": "agent/diagnostic", "params": { threadId: string, turnId: string, severity: DiagnosticSeverity, code: string, message: string, } } | { "method": "provider/attempt", "params": { observation: RequestObservation, threadId: string, turnId: string, protocol: string, diagnosticCode: string | null, retryAfterMs: number | null, retryAfterSource: RetryAfterSource | null, } } | { "method": "turn/completed", "params": { turn: Turn, } } | { "method": "turn/controlChanged", "params": { control: ControlSnapshot, } } | { "method": "turn/error", "params": { threadId: string, turnId: string, error: TurnErrorDetail, } };

export type TurnFailureCause = "store" | "project_instructions" | "workspace" | "provider_rate_limited" | "provider_network" | "provider_timeout" | "provider_auth" | "provider_validation" | "provider_overloaded" | "provider_cancelled" | "provider_context_overflow" | "provider_unknown" | "internal";

export type TurnFailureStage = "agent_loop" | "terminal_outcome";

export type TurnModelUsage = { inputTokens: number, outputTokens: number, totalTokens: number, cachedInputTokens: number, reasoningTokens: number,
/**
 * 原始 usage 对象是否存在；为 false 时各计数保持 unknown 表示，不把缺失
 * 伪装成零消费或其它可计算金额。
 */
usagePresent: boolean,
/**
 * 该聚合表示的每个 provider 请求是否都报告了精确 usage；未报告的末次
 * 请求 usage 保持 partial 而非表示为 0。
 */
usageComplete: boolean, };

export type TurnStatus = "running" | "completed" | "failed" | "interrupted";

export type UpdateSettingsParams = { workspaceId: string, sessionId: string, selector: string, };

export type WorkbenchBootstrap = { sessionPhases: { [key in string]: SessionPhase }, generation: string, revision: number, workspaces: Array<Workspace>, sessionsByWorkspace: { [key in string]: Array<ThreadSummary> }, modelCatalog: RedactedModelCatalog, };

export type WorkbenchTurnEvent = { sessionRevision: number, } & ({ "method": "turn/started", "params": { turn: Turn, startedAt: string, } } | { "method": "turn/userMessage", "params": { threadId: string, turnId: string, item: ItemRef, text: string, } } | { "method": "item/started", "params": { threadId: string, turnId: string, item: ItemRef, } } | { "method": "item/agentMessage/delta", "params": { threadId: string, turnId: string, item: ItemRef, delta: string, } } | { "method": "item/agentThinking/delta", "params": { threadId: string, turnId: string, item: ItemRef, delta: string, } } | { "method": "tool/execution/start", "params": { threadId: string, turnId: string,
/**
 * 与历史共享的公开 occurrence 身份，不是 provider 的 wire 调用 ID。
 */
item: ItemRef, toolName: string, args: JsonValue, startedAt: string, } } | { "method": "tool/execution/update", "params": { threadId: string, turnId: string, item: ItemRef, partialResult: string, } } | { "method": "tool/execution/end", "params": { threadId: string, turnId: string, item: ItemRef, output: string, isError: boolean, diff?: string, durationMs?: number, } } | { "method": "item/completed", "params": { threadId: string, turnId: string, item: ItemRef, content?: HistoryItem, } } | { "method": "item/failed", "params": { threadId: string, turnId: string, item: ItemRef, content?: HistoryItem, error: string, } } | { "method": "agent/diagnostic", "params": { threadId: string, turnId: string, severity: DiagnosticSeverity, code: string, message: string, } } | { "method": "provider/attempt", "params": { observation: RequestObservation, threadId: string, turnId: string, protocol: string, diagnosticCode: string | null, retryAfterMs: number | null, retryAfterSource: RetryAfterSource | null, } } | { "method": "turn/completed", "params": { turn: Turn, } } | { "method": "turn/controlChanged", "params": { control: ControlSnapshot, } } | { "method": "turn/error", "params": { threadId: string, turnId: string, error: TurnErrorDetail, } });

export type Workspace = { workspaceId: string, name: string, root: string, };

export type WorkspaceAddParams = { root: string, };

export type WorkspaceParams = { workspaceId: string, };

export type WorkspaceRenameParams = { workspaceId: string, name: string, };

export interface RpcContract {
  "workbench.bootstrap": { params: EmptyParams; result: WorkbenchBootstrap }
  "directory.pick": { params: EmptyParams; result: DirectoryPickResult }
  "file.search": { params: FileSearchParams; result: Array<FileCandidate> }
  "skills.list": { params: SkillsListParams; result: SkillCatalog }
  "workspace.add": { params: WorkspaceAddParams; result: Workspace }
  "workspace.remove": { params: WorkspaceParams; result: null }
  "workspace.rename": { params: WorkspaceRenameParams; result: null }
  "model.saveProvider": { params: ProviderSaveParams; result: null }
  "model.setApiKey": { params: ApiKeyParams; result: null }
  "model.discover": { params: DiscoverModelsParams; result: Array<DiscoveredModel> }
  "model.removeProvider": { params: ProviderParams; result: null }
  "session.create": { params: SessionCreateParams; result: SessionReadResult }
  "session.read": { params: SessionReadParams; result: SessionReadResult }
  "session.rename": { params: SessionRenameParams; result: null }
  "session.archive": { params: SessionParams; result: null }
  "session.submit": { params: SessionTextParams; result: null }
  "session.steer": { params: SessionTextParams; result: null }
  "session.followUp": { params: SessionTextParams; result: null }
  "session.queueWithdraw": { params: QueueControlParams; result: null }
  "session.queueReplace": { params: QueueReplaceParams; result: null }
  "session.queueSendNow": { params: QueueControlParams; result: null }
  "session.abort": { params: SessionParams; result: null }
  "session.compact": { params: SessionParams; result: null }
  "session.updateSettings": { params: UpdateSettingsParams; result: null }
}

/** 握手版本，取自 Rust 的 WORKBENCH_PROTOCOL_VERSION。 */
export const protocolVersion = 3 as const
