// Generated by singularity_protocol; cargo run -p singularity_protocol --features typescript --example export_types

export type ActiveCompactionSnapshot = { startedAt: string, };

export type ActiveTurnRuntimeSnapshot = { turnId: string, startedAt: string, };

export type ApiKeyParams = { providerId: string, apiKey: string, };

export type AppBootstrap = {
/**
 * 系统用户主目录，用于界面缩短路径；与应用数据目录无关。
 */
userHome: string | null, sessionPhases: { [key in string]: SessionPhase }, generation: string, revision: number, workspaces: Array<Workspace>, sessionsByWorkspace: { [key in string]: Array<ThreadSummary> }, modelCatalog: RedactedModelCatalog, };

export type ControlChannel = "steer" | "follow_up" | "submit";

export type ControlDisposition = "pending" | "injected" | "started_as_new_turn" | "cancelled";

export type ControlSnapshot = { controlId: string,
/**
 * 这条输入绑定到的 turn：注入活动 turn 的 steer 在接受时就已经有；等待自己
 * 那一轮的排队输入在执行开始前是 None（这时还没有可以关联的 turn）。
 */
turnId: string | null, channel: ControlChannel, sequence: number, text: string, disposition: ControlDisposition, };

export type DiagnosticSeverity = "info" | "warning" | "error";

export type DirectoryPickResult = { path: string | null, };

export type DiscoverModelsParams = { providerId: string, baseUrl: string, apiKey?: string | null, };

export type DiscoveredModel = { modelId: string, displayName: string | null, maxContextTokens: number | null, maxOutputTokens: number | null, reasoningVariants: Array<ReasoningVariant>, defaultVariant: string | null, };

export type EmptyParams = Record<string, never>;

export type FileCandidate = { path: string, };

export type FileSearchParams = { workspaceId: string, sessionId?: string | null, query: string, limit: number, };

export type HistoryItem = { "type": "request", startedAt?: string, observation: RequestObservation, } | { "type": "message", id: string, role: string, text: string, } | { "type": "thinking", id: string, text: string, } | { "type": "tool_call", id: string, name: string, args: JsonValue, } | { "type": "tool_result", id: string, output: string, diff?: string,
/**
 * read 工具真实读到的来源范围；其他工具和旧记录没有这个字段。
 */
readSource?: ReadSource, isError: boolean, durationMs?: number, } | { "type": "settings", id: string, provider: string, model: string, reasoning: string | null, } | { "type": "compaction", id: string, summary: string, };

export type ItemRef = { itemId: string, };

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null;

export type ModelConfigurationInput = { modelId: string, displayName: string | null, apiProtocol: string | null, maxContextTokens: number | null, maxOutputTokens: number | null, reasoningVariants: Array<ReasoningVariant>, defaultVariant: string | null, thinkingWireFormat: string | null,
/**
 * Chat 输出上限使用的 wire 字段名；`None` 表示发送 `max_tokens`。表单里没有
 * 这个开关的控件，但保存往返时会原样保留已有取值。
 */
chatOutputTokensField: string | null, };

export type ModelConfigurationStatus = "ready" | "missing" | "invalid";

export type ModelRequestSnapshot = { definitionsId: string, messages: Array<RequestMessage>, tools: Array<RequestTool>, modelPreferences: RequestPreferences, };

export type ProviderAttemptStatus = "started" | "ok" | "error" | "cancelled";

export type ProviderConfigurationInput = { providerId: string, displayName: string | null, baseUrl: string, models: Array<ModelConfigurationInput>, };

export type ProviderParams = { providerId: string, };

export type ProviderSaveParams = { provider: ProviderConfigurationInput,
/**
 * 只在写入时使用的新密钥；省略或传空字符串表示保留已有密钥。
 */
apiKey?: string, };

export type QueueControlParams = { workspaceId: string, sessionId: string, controlId: string, };

export type QueueReplaceParams = { workspaceId: string, sessionId: string, controlId: string, text: string, };

export type QueueSendParams = { workspaceId: string, sessionId: string, controlId?: string | null, };

export type ReadSource = {
/**
 * 实际读到的首个源文件行号；offset 省略或为 0 时规范化为 1。
 */
startLine: number,
/**
 * 正文行数；分页续读和超长单行的说明都不计入。
 */
lineCount: number, };

export type ReasoningVariant = { id: string, wireEffort: string | null, };

export type RedactedModelCatalog = { configuration: ModelConfigurationStatus, message: string | null, defaultSelector: string | null, providers: Array<RedactedProvider>, };

export type RedactedProvider = { providerId: string, displayName: string | null, baseUrl: string, credentialConfigured: boolean, models: Array<ModelConfigurationInput>, };

export type RequestMessage = { role: string, content: string, };

export type RequestObservation = {
/**
 * 查找请求详情并配对开始、结束观测的键；每次 provider attempt 生成一个，
 * 与 assistant 或 compaction 的会话条目身份无关。
 */
requestId: string,
/**
 * 为显示做的小幅投影：只含 system/developer 消息、工具和偏好。
 */
requestHead?: ModelRequestSnapshot, purpose: RequestPurpose, ordinal: number, attempt: number, provider: string, model: string, status: ProviderAttemptStatus, durationMs: number,
/**
 * 首个生成增量到请求完成的耗时；旧记录未采集时保持未知。
 */
decodeMs?: number,
/**
 * 供应商有效总量，缺失时由已知输入输出相加得到。
 */
totalTokens?: number, inputTokens: number | null, outputTokens: number | null, cachedInputTokens: number | null, error: string | null,
/**
 * 这次 attempt 的稳定诊断码：它和 `error` 类别一起构成可以持久回放的失败
 * 事实，实时事件和历史读取都从这一份记录派生。
 */
diagnosticCode?: string,
/**
 * 检查请求详情时失败；不影响 provider 的结果，也不影响会话能否恢复。
 */
requestError?: string, };

export type RequestPreferences = { maxOutputTokens: number | null, };

export type RequestPurpose = "generation" | "compaction";

export type RequestTool = { name: string, description: string, parametersSchema: JsonValue, };

export type RpcError = { code: RpcErrorCode, message: string, recovery: string, };

export type RpcErrorCode = "invalid_request" | "workspace_not_found" | "workspace_busy" | "session_not_found" | "session_busy" | "control_not_found" | "configuration_invalid" | "configuration_partially_saved" | "provider_unavailable" | "conflict" | "internal";

export type RpcResponse = { version: number, ok: boolean, result?: JsonValue, error?: RpcError, };

export type SessionModelUsage = {
/**
 * 输入合计（包含命中缓存的那部分）。
 */
inputTokens: number,
/**
 * 已知的缓存输入合计；仅 cache_usage_complete 为真时可计算命中率。
 */
cachedInputTokens: number, outputTokens: number, totalTokens: number,
/**
 * 同时具有生成耗时和输出计数的样本，用于计算 TPS。
 */
decodeTokens: number, decodeMs: number,
/**
 * 所有请求都明确报告了缓存输入用量。
 */
cacheUsageComplete: boolean,
/**
 * 计入统计的请求耗时合计（毫秒），含等待首个 token。
 */
generationMs: number,
/**
 * 是否有请求报告了 usage；为 false 时上面的计数不含任何真实消费。
 */
usagePresent: boolean,
/**
 * 账本里每个请求都报告了 usage；为 false 时上面的计数只是下界，不是全量。
 */
usageComplete: boolean, };

export type SessionParams = { workspaceId: string, sessionId: string, };

export type SessionPhase = "idle" | "reserved" | "running" | "compacting" | "stopping";

export type SessionReadParams = { workspaceId: string, sessionId: string, beforeTurn?: string | null, limit: number, };

export type SessionReadResult = { history: ThreadReadPage, runtime: SessionRuntime, activeEvents: Array<TurnEventEnvelope>, };

export type SessionRenameParams = { workspaceId: string, sessionId: string, name: string, };

export type SessionRuntime = { sessionRevision: number, phase: SessionPhase, selector: string | null, modelContextWindow: number | null, pendingControls: Array<ControlSnapshot>, activeTurn: ActiveTurnRuntimeSnapshot | null, activeCompaction: ActiveCompactionSnapshot | null, terminal: SessionTerminalSnapshot | null, };

export type SessionTerminalSnapshot = { source: SessionTerminalSource, status: TurnStatus, message: string | null, };

export type SessionTerminalSource = "turn" | "compaction";

export type SessionTextParams = { workspaceId: string, sessionId: string, text: string, };

export type SkillCatalog = { skills: Array<SkillMetadata>, diagnostics: Array<string>, };

export type SkillMetadata = { name: string, description: string, };

export type SkillsListParams = { workspaceId: string, sessionId?: string | null, };

export type StreamEnvelope = { version: number, generation: string, revision: number, } & ({ "type": "ready", payload: EmptyParams, } | { "type": "app_changed", payload: AppBootstrap, } | { "type": "session_changed", sessionId: string, payload: SessionRuntime, } | { "type": "turn_event", sessionId: string, payload: TurnEventEnvelope, } | { "type": "session_settled", sessionId: string, payload: SessionRuntime, } | { "type": "resync_required", payload: EmptyParams, });

export type ThreadReadPage = { summary: ThreadSummary, turns: Array<ThreadTurn>, nextCursor: string | null, };

export type ThreadSummary = { threadId: string, cwd: string, createdAt: string, updatedAt: string, title: string | null, model: string | null, status: TurnStatus | null,
/**
 * 最近一次被中断的 run，在账本里有明确的用户取消记录。
 */
manuallyStopped: boolean, turnCount: number,
/**
 * 整份账本的累计模型用量。它只在生成快照时更新，运行中回合的增量由调用方
 * 从活动事件里另算（读盘的冻结窗口保证两者不重叠），所以这里不是实时值。
 */
usage: SessionModelUsage, };

export type ThreadTurn = { turnId: string | null,
/**
 * 该轮的终态；只有开始标记、还没结束的轮是 running（崩溃遗留的会被整体
 * 状态投影修正为 interrupted），前导组是 null。
 */
status: TurnStatus | null,
/**
 * 该轮失败终态落盘下来的细节；成功、中断、前导组，以及没记录细节的旧日志都是 None。
 * 它和实时的 `turn/error` 事件表达同一个概念，重读历史时不依赖 runtime 最近一次的错误文本。
 */
error?: TurnErrorDetail,
/**
 * 该轮的公开条目，按会话顺序排列。
 */
items: Array<HistoryItem>, };

export type Turn = { turnId: string, threadId: string, status: TurnStatus,
/**
 * provider usage 的投影（评估工具的数据来源）。provider 可能不报告 usage；缺失时本字段是
 * None，不把未知伪装成零。请求观测写入 JSONL，重启后可聚合历史用量。
 */
usage?: TurnModelUsage, };

export type TurnErrorDetail = { cause: TurnFailureCause, message: string, };

export type TurnEventEnvelope = { sessionRevision: number, } & ({ "method": "turn/started", "params": { turn: Turn, startedAt: string, } } | { "method": "turn/userMessage", "params": { threadId: string, turnId: string, item: ItemRef, text: string, } } | { "method": "item/started", "params": { threadId: string, turnId: string, item: ItemRef, } } | { "method": "item/agentMessage/delta", "params": { threadId: string, turnId: string, item: ItemRef, delta: string, } } | { "method": "item/agentThinking/delta", "params": { threadId: string, turnId: string, item: ItemRef, delta: string, } } | { "method": "tool/execution/start", "params": { threadId: string, turnId: string,
/**
 * 与历史共享的公开 occurrence 身份，不是 provider 在 wire 上的调用 ID。
 */
item: ItemRef, toolName: string, args: JsonValue, startedAt: string, } } | { "method": "tool/execution/update", "params": { threadId: string, turnId: string, item: ItemRef, partialResult: string, } } | { "method": "tool/execution/end", "params": { threadId: string, turnId: string, item: ItemRef, output: string, isError: boolean, diff?: string, durationMs?: number,
/**
 * read 工具真实读到的来源范围；其他工具和旧记录没有这个字段。
 */
readSource?: ReadSource, } } | { "method": "item/discarded", "params": { threadId: string, turnId: string, item: ItemRef, } } | { "method": "item/completed", "params": { threadId: string, turnId: string, item: ItemRef, content?: HistoryItem, } } | { "method": "item/failed", "params": { threadId: string, turnId: string, item: ItemRef, content?: HistoryItem, error: string, } } | { "method": "agent/diagnostic", "params": { threadId: string, turnId: string, severity: DiagnosticSeverity, code: string, message: string, } } | { "method": "provider/attempt", "params": { observation: RequestObservation, threadId: string, turnId: string, protocol: string, retryAfterMs: number | null, } } | { "method": "turn/completed", "params": { turn: Turn, } } | { "method": "turn/controlChanged", "params": { control: ControlSnapshot, } } | { "method": "turn/error", "params": { threadId: string, turnId: string, error: TurnErrorDetail, } });

export type TurnFailureCause = "store" | "project_instructions" | "workspace" | "provider_rate_limited" | "provider_network" | "provider_timeout" | "provider_auth" | "provider_validation" | "provider_overloaded" | "provider_cancelled" | "provider_context_overflow" | "provider_unknown" | "internal";

export type TurnModelUsage = { inputTokens: number, outputTokens: number, totalTokens: number, cachedInputTokens: number, reasoningTokens: number,
/**
 * 这次聚合里是否至少有一个请求完整上报了输入和输出计数（两项都齐全）。
 * 为 false 时各个计数保持「未知」的含义，不把缺失伪装成零消费或可计算的金额。
 */
usagePresent: boolean,
/**
 * 这个聚合覆盖的每个 provider 请求是否都报告了精确 usage；没报告的请求
 * 让结果保持「不完整」，而不是把它表示成 0。
 */
usageComplete: boolean, };

export type TurnStatus = "running" | "completed" | "failed" | "interrupted";

export type UpdateSettingsParams = { workspaceId: string, sessionId: string, selector: string, };

export type Workspace = { workspaceId: string, name: string, root: string, };

export type WorkspaceAddParams = { root: string, };

export type WorkspaceParams = { workspaceId: string, };

export type WorkspaceRenameParams = { workspaceId: string, name: string, };

export interface RpcContract {
  "app.bootstrap": { params: EmptyParams; result: AppBootstrap }
  "directory.pick": { params: EmptyParams; result: DirectoryPickResult }
  "file.search": { params: FileSearchParams; result: Array<FileCandidate> }
  "skills.list": { params: SkillsListParams; result: SkillCatalog }
  "workspace.add": { params: WorkspaceAddParams; result: Workspace }
  "workspace.remove": { params: WorkspaceParams; result: null }
  "workspace.rename": { params: WorkspaceRenameParams; result: null }
  "model.saveProvider": { params: ProviderSaveParams; result: null }
  "model.setApiKey": { params: ApiKeyParams; result: null }
  "model.discover": { params: DiscoverModelsParams; result: Array<DiscoveredModel> }
  "model.removeProvider": { params: ProviderParams; result: null }
  "session.create": { params: WorkspaceParams; result: SessionReadResult }
  "session.read": { params: SessionReadParams; result: SessionReadResult }
  "session.rename": { params: SessionRenameParams; result: null }
  "session.archive": { params: SessionParams; result: null }
  "session.submit": { params: SessionTextParams; result: null }
  "session.steer": { params: SessionTextParams; result: null }
  "session.followUp": { params: SessionTextParams; result: null }
  "session.queueWithdraw": { params: QueueControlParams; result: null }
  "session.queueReplace": { params: QueueReplaceParams; result: null }
  "session.queueSendNow": { params: QueueSendParams; result: null }
  "session.abort": { params: SessionParams; result: null }
  "session.compact": { params: SessionParams; result: null }
  "session.updateSettings": { params: UpdateSettingsParams; result: null }
}

/** 握手版本，取自 Rust 的 PROTOCOL_VERSION。 */
export const protocolVersion = 8 as const
