[package]
name = "singularity_model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
autotests = false

[features]
test-support = []

[lints]
workspace = true

[dependencies]
bytes.workspace = true
cap-fs-ext.workspace = true
cap-std.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
singularity_core = { path = "../core" }
singularity_protocol = { path = "../protocol" }
time.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.52"
features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
]
