from __future__ import annotations

SQLITE_BUSY_TIMEOUT_MS = 5000

ATOMIC_WRITE_REPLACE_RETRY_ATTEMPTS = 8
ATOMIC_WRITE_REPLACE_RETRY_BASE_SECONDS = 0.05

DEFAULT_TOOL_EXECUTION_TIMEOUT_SECONDS = 120.0
DEFAULT_REGISTERED_TOOL_TIMEOUT_SECONDS = 5.0
DEFAULT_TOOL_MAX_OUTPUT_CHARS = 20000
DEFAULT_TOOL_CACHE_MAX_ENTRIES = 128
DEFAULT_TOOL_RETRY_MAX_ATTEMPTS = 1
MAX_TOOL_RETRY_ATTEMPTS = 5
EVALUATION_PREPARE_TIMEOUT_SECONDS = 120.0
BENCHMARK_VERIFICATION_TIMEOUT_SECONDS = 120.0
EVALUATION_TASK_VERIFICATION_TIMEOUT_SECONDS = int(BENCHMARK_VERIFICATION_TIMEOUT_SECONDS)
WINDOWS_RUNNER_DEFAULT_TIMEOUT_SECONDS = 120.0
WINDOWS_RUNNER_PROCESS_POLL_INTERVAL_SECONDS = 0.02
WINDOWS_SANDBOX_ACL_COMMAND_TIMEOUT_SECONDS = 120.0
PROCESS_TERMINATION_GRACE_SECONDS = 1.0

SANDBOX_READONLY_ANALYSIS_TIMEOUT_SECONDS = 30
SANDBOX_GENERATED_CODE_TIMEOUT_SECONDS = 30
SANDBOX_PACKAGE_OPERATION_TIMEOUT_SECONDS = 180
SANDBOX_LONG_RUNNING_SERVICE_TIMEOUT_SECONDS = 300
SANDBOX_ISOLATED_VERIFICATION_TIMEOUT_SECONDS = 120
SANDBOX_STANDARD_OUTPUT_CHARS = 20000
SANDBOX_PACKAGE_OUTPUT_CHARS = 30000
SANDBOX_VERIFICATION_OUTPUT_CHARS = 40000
SANDBOX_VERIFICATION_MAX_ARTIFACT_BYTES = 20 * 1024 * 1024

PYTHON_PYTEST_TIMEOUT_SECONDS = 180
PYTHON_RUFF_TIMEOUT_SECONDS = 120
PYTHON_MYPY_TIMEOUT_SECONDS = 180

WORKSPACE_MEDIUM_DIFF_LINE_THRESHOLD = 100
WORKSPACE_REVIEW_DIFF_LINE_THRESHOLD = 500
CONTEXT_SUMMARY_MAX_TOKENS = 160

MODEL_RETRY_MAX_ATTEMPTS = 3
MODEL_RETRY_BACKOFF_SECONDS = 0.25
MODEL_RETRY_JITTER_RATIO = 0.2

CAPABILITY_SLA_REQUIRED_THRESHOLDS_SECONDS = {
    "wall": 300.0,
    "agent_loop": 210.0,
    "provider": 55.0,
    "sandbox": 50.0,
    "dependency_setup": 35.0,
}
CAPABILITY_SLA_OPTIONAL_THRESHOLDS_SECONDS = {
    "verification": 10.0,
    "unattributed_time": 15.0,
}
